kind: Secret
apiVersion: v1
metadata:
  name: nodejs-mongodb-example
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
stringData:
  database-admin-password: c2VjcmV0
  database-password: c2VjcmV0
  database-user: bHVrZQ==