kind: Secret
apiVersion: v1
metadata:
  name: nodejs-mongodb-example
  labels:
    label1: jajaja1
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
stringData:
  database-admin-password: secret1
  database-password: secret
  database-user: luke